config/routes.rb
Rails.application.routes.draw do

  get 'periods/new'

  root 'properties#index' #this is the real root!!!


  resources :researches
  # root 'researches#index' #this root is just for testing Stripe payments
  get 'research', to: 'researches#index', as: 'extensive'
  resources :charges, only: [:create]




  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  devise_for :people


  resources :chat_rooms, only: [:new, :create, :show, :index] do
  resources :messages, only: [:create]
  end

  # root 'chat_rooms#index'
  mount ActionCable.server => '/cable'

  get '/chat_rooms', to: 'chat_rooms#index'

  get 'session/show'


  resources :users

  get '/properties', to: 'properties#show'
  get '/analyze/:id', to: 'properties#analyze', as: 'analyze'
  get '/videochat', to: 'sessions#show'
  # get '/signup', to: 'users#new'

  get '/googlemap', to: 'properties#google_satellite_view'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :person
  has_many :messages, dependent: :destroy
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :person
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  after_create_commit { MessageBroadcastJob.perform_later(self) }

 def timestamp
   created_at.strftime('%H:%M:%S %d %B %Y')
 end
 
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    email.split('@')[0]
  end
end

app/models/property.rb
# **************M O D E L**************
class Property < ApplicationRecord
  belongs_to :user

  def self.build_from_api(address, citystatezip)
    return new if (address.empty? || citystatezip.empty?)
    address = address.to_s.gsub(" ","+")
    citystatezip = citystatezip.to_s.gsub(" ", "+").gsub(/,/,"%2C")
    zillow_api = "http://www.zillow.com/webservice/GetDeepSearchResults.htm?zws-id=X1-ZWz19hai5nqayz_6ttia&address=#{address}&citystatezip=#{citystatezip}"
    results = HTTParty.get(zillow_api)["searchresults"]["response"]["results"]["result"]

    zillow_id = results["zpid"].to_i
    street = results["address"]["street"]
    city = results["address"]["city"]
    state = results["address"]["state"]
    zipcode = results["address"]["zipcode"]
    latitude = results["address"]["latitude"]
    longitude = results["address"]["longitude"]
    sqft = results["finishedSqFt"].to_i
    bathrooms = results["bathrooms"].to_i
    bedrooms = results["bedrooms"].to_i
    estimate = results["zestimate"]["amount"]["__content__"].to_i
    valuechange = results["zestimate"]["valueChange"]["__content__"].to_i
    a = Property.new({estimate: estimate, zillow_id: zillow_id, street: street, city: city, state: state, zipcode: zipcode, latitude: latitude, longitude: longitude, sqft: sqft, baths:bathrooms, bedrooms: bedrooms, valuechange: valuechange})
    a.save(:validate => false)
    return a
    # create({estimate: estimate, zillow_id: zillow_id, street: street, city: city, state: state, zipcode: zipcode, latitude: latitude, longitude: longitude, sqft: sqft, baths:bathrooms, bedrooms: bedrooms, valuechange: valuechange})
  end

  def chart5year
    get_chart = "http://www.zillow.com/webservice/GetChart.htm?zws-id=X1-ZWz19hai5nqayz_6ttia&unit-type=dollar&zpid=#{zillow_id}&width=600&height=300&chartDuration=5years"
    chart = HTTParty.get(get_chart)['chart']['response']['url']
  end

  def chart10year
    get_chart = "http://www.zillow.com/webservice/GetChart.htm?zws-id=X1-ZWz19hai5nqayz_6ttia&unit-type=dollarx&zpid=#{zillow_id}&width=600&height=300&chartDuration=10years"
    chart = HTTParty.get(get_chart)['chart']['response']['url']
  end

  def comparibles
    second_zillow_api = "http://www.zillow.com/webservice/GetDeepComps.htm?zws-id=X1-ZWz19hai5nqayz_6ttia&zpid=#{zillow_id}&count=#{10}"
    comparables = HTTParty.get(second_zillow_api)["comps"]["response"]["properties"]["comparables"]["comp"]
  end



end

app/models/research.rb
class Research < ApplicationRecord
  validates_presence_of :title, :price
end

app/models/user.rb
# **************M O D E L**************
class User < ApplicationRecord
  has_secure_password
  has_many :properties
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
      @research = Research.find(params[:book_id])

      # Amount is in cents
      @amount = @research.price
      @amount = @amount.to_i

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => @research.title,
        :currency    => 'usd'
      )
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_person! 

 def show
   @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
   @message = Message.new
 end

 def index
   @chat_rooms = ChatRoom.all
 end

 def new
   @chat_room = ChatRoom.new
 end

 def create
   @chat_room = current_person.chat_rooms.build(chat_room_params)
   if @chat_room.save
     flash[:success] = 'Chat room added!'
     redirect_to chat_rooms_path
   else
     render 'new'
   end
 end

 private

 def chat_room_params
   params.require(:chat_room).permit(:title)
 end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    p @contact.valid?, @contact.spam?
    require 'pp'
    pp @contact.errors.full_messages
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
 before_action :set_chat_room, only: [:create]

 def create
   @message = @chat_room.messages.new(message_params)
   @message.user = current_user

   if @message.save
     redirect_to @chat_room
   end
   p @message.errors.messages
 end

 private
 def message_params
   params.require(:message).permit(:body)
 end

 def set_chat_room
   @chat_room = ChatRoom.find(params[:chat_room_id])
 end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def show
   @opentok = OpenTok::OpenTok.new('45728832', 'cfdc084f981cd5167065628223ab799a5d359e77')
   @session_id = @opentok.create_session.session_id
   @api_key = '45728832'
   @token = @opentok.generate_token(@session_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      Property.last.update(user_id: @user.id)
      redirect_to root_path, notice: 'Created user'
    else
      return render action: 'new'
    end
  end

  def show

  end

  private

  def user_params
    params.require(:user).
    permit(:username,
    :password,
    :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(person, opts = {})
    # opts[:alt] = person.name
    # image_tag = "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(person.email)}?s=#{opts.delete(:size) { 40 }}",
    #             opts
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, your purchase was successful!</h2>

app/views/chat_rooms/_chat_room.html.erb
<div class="main-container">
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>
</div>

app/views/chat_rooms/index.html.erb
<div class="container main-container">
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
 <%= render @chat_rooms %>
</ul>
</div>

app/views/chat_rooms/new.html.erb
<div class="container main-container">
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
 <div class="form-group">
   <%= f.label :title %>
   <%= f.text_field :title, autofocus: true, class: 'form-control' %>
 </div>

 <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>
</div>

app/views/chat_rooms/show.html.erb
<div class="container main-container">
  <h1><%= @chat_room.title %></h1>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
 <%= render @chat_room.messages %>
</div>

<%= form_for([@chat_room, @message]) do |f| %>
 <div class="form-group">
   <%= f.label :body %>
   <%= f.text_area :body, class: 'form-control' %>
   <small class="text-muted">From 2 to 1000 characters</small>
 </div>

 <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>
</div>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="container">
<div class="jumbotron">
<!-- <div align="center"> -->
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
<!-- </div> -->
</div>
</div>

app/views/messages/_message.html.erb
<div class="card">
 <div class="card-block">
   <div class="row">
     <div class="col-md-1">
       <%= gravatar_for message.person %>
     </div>
     <div class="col-md-11">
       <p class="card-text">
         <span class="text-muted"><%= message.person.name %> at <%= message.timestamp %> says</span><br>
         <%= message.body %>
       </p>
     </div>
   </div>
 </div>
</div>

app/views/periods/new.html.erb
<h1>Periods#new</h1>
<p>Find me in app/views/periods/new.html.erb</p>

app/views/session/show.html.erb
<!-- <!DOCTYPE html>
<html>
 <head>
   <meta charset="utf-8" />
   <title>OpenTok Hello World</title> -->
<div class="main-container">
   <script type="text/javascript">
       var apiKey = '<%= @api_key %>';
       var sessionId = '<%= @session_id %>';
       var token = '<%= @token %>';

       var session = OT.initSession(apiKey, sessionId);
       var publisher = OT.initPublisher('publisher', {
         insertMode: 'append',
         width: '100%',
         height: '800px'
       });

       // Initialize a Publisher, and place it into the element with id="publisher"
       // var publisher = TB.initPublisher(apiKey, 'publisher');

       // Attach event handlers
       session.on('streamCreated', function(event){
         var subscriberProperties = {insertMode: 'append'};
         var subscriber = session.subscribe(event.stream,
           'subscriberContainer',
           subscriberProperties,
           function (error) {
             if (error) {
               console.log(error);
             }
             else {
               console.log("Subscriber added.");
             }
           });
         });

       session.connect(token, function(error){
         if (error) {
           console.log("Aint working");
         } else {
           console.log("working fine!");
           session.publish(publisher);
         }
       });


   </script>
   <!-- <script src="..assets/javascript/helloworld.js"></script> -->
 <!-- </head> -->
 <!-- <body> -->
   <h2>Welcome to Costumer Support</h2>
   <div class="videobox"></div>

   <div id="publisher"></div>

   <div id="subscribers"></div>
</div>
 <!-- </body>
</html> -->