config/routes.rb
Rails.application.routes.draw do

  get 'periods/new'

  root 'properties#index' #this is the real root!!!


  resources :researches
  # root 'researches#index' #this root is just for testing Stripe payments
  get 'research', to: 'researches#index', as: 'extensive'
  resources :charges, only: [:create]




  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  devise_for :people


  resources :chat_rooms, only: [:new, :create, :show, :index] do
  resources :messages, only: [:create]
  end

  # root 'chat_rooms#index'
  mount ActionCable.server => '/cable'

  get '/chat_rooms', to: 'chat_rooms#index'

  get 'session/show'


  resources :users

  get '/properties', to: 'properties#show'
  get '/analyze/:id', to: 'properties#analyze', as: 'analyze'
  get '/videochat', to: 'sessions#show'
  # get '/signup', to: 'users#new'

  get '/googlemap', to: 'properties#google_satellite_view'
end

app/models/research.rb
class Research < ApplicationRecord
  validates_presence_of :title, :price
end

app/controllers/researches_controller.rb
class ResearchesController < ApplicationController
  before_action :set_research, only: [:show, :edit, :update, :destroy]

  # GET /researches
  # GET /researches.json
  def index
    @researches = Research.all
  end

  # GET /researches/1
  # GET /researches/1.json
  def show
  end

  # GET /researches/new
  def new
    @research = Research.new
  end

  # GET /researches/1/edit
  def edit
  end

  # POST /researches
  # POST /researches.json
  def create
    @research = Research.new(research_params)

    respond_to do |format|
      if @research.save
        format.html { redirect_to @research, notice: 'Research was successfully created.' }
        format.json { render :show, status: :created, location: @research }
      else
        format.html { render :new }
        format.json { render json: @research.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /researches/1
  # PATCH/PUT /researches/1.json
  def update
    respond_to do |format|
      if @research.update(research_params)
        format.html { redirect_to @research, notice: 'Research was successfully updated.' }
        format.json { render :show, status: :ok, location: @research }
      else
        format.html { render :edit }
        format.json { render json: @research.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /researches/1
  # DELETE /researches/1.json
  def destroy
    @research.destroy
    respond_to do |format|
      format.html { redirect_to researches_url, notice: 'Research was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_research
      @research = Research.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def research_params
      params.require(:research).permit(:title, :price)
    end
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/views/researches/_form.html.erb
<%= form_for(research) do |f| %>
  <% if research.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(research.errors.count, "error") %> prohibited this research from being saved:</h2>

      <ul>
      <% research.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price, :placeholder => "enter amount in cents" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/researches/edit.html.erb
<h1>Editing Research</h1>

<%= render 'form', research: @research %>

<%= link_to 'Show', @research %> |
<%= link_to 'Back', researches_path %>

app/views/researches/index.html.erb
<div class="main-container">
  <div class="jumbotron">

    <p id="notice"><%= notice %></p>

    <h1>Extensive Property Research</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Price</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @researches.each do |research| %>
          <tr>
            <td><%= research.title %></td>
            <td><%= research.price/100 %></td>
            <td><%= link_to 'Show', research %></td>
            <!-- <td><%= link_to 'Edit', edit_research_path(research) %></td>
            <td><%= link_to 'Destroy', research, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Research', new_research_path %>
  </div>
</div>

app/views/researches/new.html.erb
<div class="main-container">
  <h1>New Research</h1>

  <%= render 'form', research: @research %>

  <%= link_to 'Back', researches_path %>
</div>

app/views/researches/show.html.erb
<div class="main-container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @research.title %>
  </p>

  <%= form_tag charges_path do %>
    <article>
      <label class="amount">
        <span>Price: $<%= @research.price/100 %></span>
      </label>
    </article>

    <%= hidden_field_tag 'book_id', @research.id %>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description=<%= @research.title %>
            data-amount=<%= @research.price %>
            data-locale="auto">
     </script>
   <% end %>


  <%= link_to 'Edit', edit_research_path(@research) %> |
  <%= link_to 'Back', researches_path %>
</div>