config/routes.rb
Rails.application.routes.draw do

  get 'periods/new'

  root 'properties#index' #this is the real root!!!


  resources :researches
  # root 'researches#index' #this root is just for testing Stripe payments
  get 'research', to: 'researches#index', as: 'extensive'
  resources :charges, only: [:create]




  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  devise_for :people


  resources :chat_rooms, only: [:new, :create, :show, :index] do
  resources :messages, only: [:create]
  end

  # root 'chat_rooms#index'
  mount ActionCable.server => '/cable'

  get '/chat_rooms', to: 'chat_rooms#index'

  get 'session/show'


  resources :users

  get '/properties', to: 'properties#show'
  get '/analyze/:id', to: 'properties#analyze', as: 'analyze'
  get '/videochat', to: 'sessions#show'
  # get '/signup', to: 'users#new'

  get '/googlemap', to: 'properties#google_satellite_view'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :person
  has_many :messages, dependent: :destroy
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :person
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  after_create_commit { MessageBroadcastJob.perform_later(self) }

 def timestamp
   created_at.strftime('%H:%M:%S %d %B %Y')
 end
 
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    email.split('@')[0]
  end
end

app/models/property.rb
# **************M O D E L**************
class Property < ApplicationRecord
  belongs_to :user

  def self.build_from_api(address, citystatezip)
    return new if (address.empty? || citystatezip.empty?)
    address = address.to_s.gsub(" ","+")
    citystatezip = citystatezip.to_s.gsub(" ", "+").gsub(/,/,"%2C")
    zillow_api = "http://www.zillow.com/webservice/GetDeepSearchResults.htm?zws-id=X1-ZWz19hai5nqayz_6ttia&address=#{address}&citystatezip=#{citystatezip}"
    results = HTTParty.get(zillow_api)["searchresults"]["response"]["results"]["result"]

    zillow_id = results["zpid"].to_i
    street = results["address"]["street"]
    city = results["address"]["city"]
    state = results["address"]["state"]
    zipcode = results["address"]["zipcode"]
    latitude = results["address"]["latitude"]
    longitude = results["address"]["longitude"]
    sqft = results["finishedSqFt"].to_i
    bathrooms = results["bathrooms"].to_i
    bedrooms = results["bedrooms"].to_i
    estimate = results["zestimate"]["amount"]["__content__"].to_i
    valuechange = results["zestimate"]["valueChange"]["__content__"].to_i
    a = Property.new({estimate: estimate, zillow_id: zillow_id, street: street, city: city, state: state, zipcode: zipcode, latitude: latitude, longitude: longitude, sqft: sqft, baths:bathrooms, bedrooms: bedrooms, valuechange: valuechange})
    a.save(:validate => false)
    return a
    # create({estimate: estimate, zillow_id: zillow_id, street: street, city: city, state: state, zipcode: zipcode, latitude: latitude, longitude: longitude, sqft: sqft, baths:bathrooms, bedrooms: bedrooms, valuechange: valuechange})
  end

  def chart5year
    get_chart = "http://www.zillow.com/webservice/GetChart.htm?zws-id=X1-ZWz19hai5nqayz_6ttia&unit-type=dollar&zpid=#{zillow_id}&width=600&height=300&chartDuration=5years"
    chart = HTTParty.get(get_chart)['chart']['response']['url']
  end

  def chart10year
    get_chart = "http://www.zillow.com/webservice/GetChart.htm?zws-id=X1-ZWz19hai5nqayz_6ttia&unit-type=dollarx&zpid=#{zillow_id}&width=600&height=300&chartDuration=10years"
    chart = HTTParty.get(get_chart)['chart']['response']['url']
  end

  def comparibles
    second_zillow_api = "http://www.zillow.com/webservice/GetDeepComps.htm?zws-id=X1-ZWz19hai5nqayz_6ttia&zpid=#{zillow_id}&count=#{10}"
    comparables = HTTParty.get(second_zillow_api)["comps"]["response"]["properties"]["comparables"]["comp"]
  end



end

app/models/research.rb
class Research < ApplicationRecord
  validates_presence_of :title, :price
end

app/models/user.rb
# **************M O D E L**************
class User < ApplicationRecord
  has_secure_password
  has_many :properties
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
      @research = Research.find(params[:book_id])

      # Amount is in cents
      @amount = @research.price
      @amount = @amount.to_i

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => @research.title,
        :currency    => 'usd'
      )
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    p @contact.valid?, @contact.spam?
    require 'pp'
    pp @contact.errors.full_messages
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
 before_action :set_chat_room, only: [:create]

 def create
   @message = @chat_room.messages.new(message_params)
   @message.user = current_user

   if @message.save
     redirect_to @chat_room
   end
   p @message.errors.messages
 end

 private
 def message_params
   params.require(:message).permit(:body)
 end

 def set_chat_room
   @chat_room = ChatRoom.find(params[:chat_room_id])
 end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      Property.last.update(user_id: @user.id)
      redirect_to root_path, notice: 'Created user'
    else
      return render action: 'new'
    end
  end

  def show

  end

  private

  def user_params
    params.require(:user).
    permit(:username,
    :password,
    :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(person, opts = {})
    # opts[:alt] = person.name
    # image_tag = "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(person.email)}?s=#{opts.delete(:size) { 40 }}",
    #             opts
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<!-- Side NavBar -->

<div class="col-sm-2 no-padding side-nav navbar-fixed-side">
 <nav class="nav-wrap">
   <ul class="nav">


   <li class="nav-group" style="white-space: nowrap;">
     <div>
       <i class="fa fa-home house_icon" aria-hidden="true" style="font-size:20px;"></i>
       <%= link_to 'Property Info', properties_path, class: 'nav-text'%>
     </div>
   </li>



   <li class="nav-group">

     <div>
       <i class="fa fa-bar-chart" aria-hidden="true" style="font-size:18px;"></i>
       <%= link_to 'Analyze', analyze_path(@property), class: 'nav-text'%>
     </div>
   </li>

   <li class="nav-group">
     <div>
       <i class="fa fa-globe" aria-hidden="true" style="font-size:18px;"></i>
       <%= link_to 'Google Satellite View', googlemap_path, class: 'nav-text'%>
    </div>
   </li>


    <li class="nav-group">
      <div>
        <i class="fa fa-comments" aria-hidden="true" style="font-size:18px;"></i>
        <%= link_to 'Video Chat', videochat_path, class: 'nav-text' %>
      </div>
    </li>

   <li class="nav-group">
     <div>
       <i class="fa fa-comments" aria-hidden="true" style="font-size:18px;"></i>
       <%= link_to 'Customer Support', chat_rooms_path, class: 'nav-text' %>
     </div>
   </li>


   <li class="nav-group">
     <div>
       <i class="fa fa-line-chart" aria-hidden="true" style="font-size:18px;"></i>
       <%= link_to 'Extensive Research', extensive_path, class: 'nav-text' %>
     </div>
   </li>

   <li class="nav-group">
     <div>
       <i class="fa fa-thumbs-up" aria-hidden="true" style="font-size:18px;"></i>
       <%= link_to 'Give us your Feedback', contacts_path, class: 'nav-text' %>
     </div>
   </li>



 </ul>
 </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Flipthis" %></title>
    <%= csrf_meta_tags %>
    <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Monoton|Raleway" rel="stylesheet"> -->
    <link href="https://fonts.googleapis.com/css?family=Roboto|Monoton|Raleway|Muli:300|Roboto:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Baumans" rel="stylesheet">
    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/4f85b13015.js"></script>
  </head>
 <body>

   <div class="navbar navbar-default navbar-static-top no-margin">
     <!-- <div class="container"> -->
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <!-- <button class="nav-btn">
         <i class="fa fa-bars" aria-hidden="true"></i>
       </button> -->
       <a class="navbar-brand" href="#">Reflip</a>
         <div class="navbar-collapse collapse navbar-responsive-collapse">
       </div>
     <!-- </div> -->
   </div>

   <div class="container">
    <%# render "elements/navbar" %>
    <%# yield %>
   </div>

   <%= bootstrap_flash %>

   <%= yield %>

 </body>
</html>